SELECT 
SUM(QTD_PONTOS) AS 'Quantidade de Pontos',
EQUIPE.NOME AS 'Nome da Equipe',
MODALIDADE.NOME AS 'Modalidade'
FROM PARTIDA, PARTICIPACAO, EQUIPE, MODALIDADE
WHERE PARTICIPACAO.ID_PARTICIPACAO = PARTIDA.ID_PARTICIPACAO_VENCEDORA AND
PARTICIPACAO.ID_EQUIPE = EQUIPE.ID_EQUIPE AND
PARTICIPACAO.ID_MODALIDADE = MODALIDADE.ID_MODALIDADE AND
MODALIDADE.TIPO_MODALIDADE = 'Equipe'
GROUP BY PARTIDA.ID_PARTICIPACAO_VENCEDORA
ORDER BY SUM(QTD_PONTOS) DESC;


SELECT 
SUM(QTD_PONTOS) AS 'Quantidade de Pontos',
ATLETA.NOME AS 'Nome do Atleta',
MODALIDADE.NOME AS 'Modalidade'
FROM PARTIDA, PARTICIPACAO, ATLETA, MODALIDADE
WHERE PARTICIPACAO.ID_PARTICIPACAO = PARTIDA.ID_PARTICIPACAO_VENCEDORA AND
PARTICIPACAO.ID_ATLETA = ATLETA.ID_ATLETA AND
PARTICIPACAO.ID_MODALIDADE = MODALIDADE.ID_MODALIDADE AND
MODALIDADE.TIPO_MODALIDADE = 'Individual'
GROUP BY PARTIDA.ID_PARTICIPACAO_VENCEDORA
ORDER BY SUM(QTD_PONTOS) DESC;