DROP SCHEMA IF EXISTS CAMPEONATO;
CREATE SCHEMA CAMPEONATO;
USE CAMPEONATO;

CREATE TABLE MODALIDADE (
	ID_MODALIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME TEXT NOT NULL,
    TIPO_MODALIDADE ENUM ('Equipe', 'Individual') NOT NULL
);

CREATE TABLE GRUPO (
	ID_GRUPO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME TEXT NOT NULL,
    TIPO_GRUPO ENUM('Pontos corridos', 'Chaveamento') NOT NULL
);

CREATE TABLE EQUIPE (
	ID_EQUIPE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME TEXT NOT NULL,
    ID_MODALIDADE INT NOT NULL,
    ID_GRUPO INT NOT NULL,
    CONSTRAINT FK_ID_MODALIDADE_EQUIPE FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADE(ID_MODALIDADE),
    CONSTRAINT FK_ID_GRUPO_EQUIPE FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO)
);

CREATE TABLE ATLETA (
	ID_ATLETA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME TEXT NOT NULL,
    DATA_NASC DATETIME NOT NULL,
    ID_EQUIPE INT NOT NULL,
    CONSTRAINT FK_ID_EQUIPE_ATLETA FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE)
);

CREATE TABLE PARTICIPACAO(
	ID_PARTICIPACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_ATLETA INT NOT NULL,
    ID_EQUIPE INT NOT NULL,
    ID_GRUPO INT NOT NULL,
    ID_MODALIDADE INT NOT NULL,
    CONSTRAINT FK_ID_ATLETA_PARTICIPACAO FOREIGN KEY (ID_ATLETA) REFERENCES ATLETA(ID_ATLETA),
    CONSTRAINT FK_ID_EQUIPE_PARTICIPACAO FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE),
    CONSTRAINT FK_ID_GRUPO_PARTICIPACAO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO),
    CONSTRAINT FK_ID_MODALIDADE_PARTICIPACAO FOREIGN KEY (ID_MODALIDADE) REFERENCES MODALIDADE(ID_MODALIDADE)
);

CREATE TABLE PARTIDA (
	ID_PARTIDA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FASE ENUM('Classificatória', 'Oitava', 'Quarta', 'Semifinal', 'Final', 'Pontos corridos'),
    QTD_PONTOS INT NOT NULL,
    ID_PARTICIPACAO_VENCEDORA INT NOT NULL,
    CONSTRAINT FK_ID_PARTICIPACAO_PARTIDA FOREIGN KEY (ID_PARTICIPACAO_VENCEDORA) REFERENCES PARTICIPACAO(ID_PARTICIPACAO)
);
